name: kkk
favicon: null
layout_spectrum: 0.23556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#898b8a'
    - '#007fda'
    - '#0046bf'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
